### ISSUE TITLE
Please consider node-red-contrib- naming guidelines

### ISSUE THREAD

**Issue by knolleary** [diegopamio/node-red-contrib-ifttt#1]
Hi there - thanks for creating a node and sharing it with the community.

One request - as per our [packaging guidelines](http://nodered.org/docs/creating-nodes/packaging), we ask that 3rd party nodes use the `node-red-contrib-` prefix to their name. This ensures they don't get mistaken for nodes maintained by the project itself.

You're under no obligation to change the name, but I hope you'll consider it.

Many thanks, Nick

**Comment by diegopamio** [comment]
Sorry! Actually I thought it was the other way around. 

I've now renamed it both in the repo and in the npm registry, using this guidelines: http://stackoverflow.com/questions/28371669/renaming-a-published-npm-module 

Regards,
Diego.

**Comment by knolleary** [comment]
Thanks! Appreciate your contribution! 👍
