### ISSUE TITLE
Can't see value1, value2, value3

### ISSUE THREAD

**Issue by larkolab** [diegopamio/node-red-contrib-ifttt#10]
Hello,

I've installed v0.0.13, and trying to send a simple message with data in value1, value2 and value3, but when the activity triggers in IFTTT, I see none value:
```
Value1
    (none)
Value2
    (none)
Value3
    (none)
```

The node-red flow is simple:
inject -> function -> ifttt
with the function being:
```
msg.payload.value1 = "hello";
msg.payload.value2 = "world";
msg.payload.value3 = "again";

return msg;
```

The webhook in IFTTT is configured to send a notification with following body:
`{{Value1}} sent {{Value2}} at {{OccurredAt}}`
But I only the "OccuredAt" is being set a value, the rest remains empty.

Any idea why?

Thanks a lot

**Comment by larkolab** [comment]
AH, it works if I empty the message coming from the Inject node before setting the values

```
msg.payload = {};
msg.payload.value1 = "hello";
msg.payload.value2 = "world";
msg.payload.value3 = "again";

return msg;
```

**Comment by lorenwest** [comment]
To be clear, you weren't emptying msg.payload, you were initializing it as an object so value1-3 could be placed into it.

If your inject node set msg.payload to anything other than an object that could have value1-3 placed into it (such as an integer from an inject node), you'd need to change it to an object by setting it to `{}`.

**Comment by larkolab** [comment]
oh right, sorry! Thanks for the clarification.
And thanks for the IFTTT node! :)
