### ISSUE TITLE
Some names possibly out-dated with ifttt? 

### ISSUE THREAD

**Issue by jmikerq** [diegopamio/node-red-contrib-ifttt#14]
So I think this might be related to the changes on ifttt recently. From some of the older blog posts and what I see on ifttt, it seems like ifttt renamed what is used to call 'Maker Channel' to 'maker webhooks' or just simply 'webhooks' (at the end they are just the same HTTP requests). So without any previous experience with this awesome node, I was confused in how to setup my 'maker channel'. 

As discussed on here: [https://gist.github.com/austinhuang0131/4610dd2e19ce22b407387981479d1bae](https://gist.github.com/austinhuang0131/4610dd2e19ce22b407387981479d1bae)

**Comment by lorenwest** [comment]
Next person that goes through the setup and is confused at changing nomenclature, create a pull request, or paste the updates in this issue and I'll update the docs.

**Comment by jmikerq** [comment]
thanks!

**Comment by thomasvnl** [comment]
This was confusing me a bit too, I googled for Maker Channel (remembering that that was something a while ago on IFTTT) and it sent me to the Webhooks channel.

**Comment by lorenwest** [comment]
Just got to this. Thanks for the input - it's changed now.
