### ISSUE TITLE
Node crashes on address not found, plus possible timeout issue

### ISSUE THREAD

**Issue by TheOriginalMrWolf** [diegopamio/node-red-contrib-ifttt#15]
Hi,

Thanks for making this handy node!

Unfortunately I've found a small issue whereby Node Red crashes if the IFTTT node can't connect to IFTTT (due, for instance, to no internet connectivity).

The culprit is around line 34 of node-red-contrib-ifttt/nodes/ifttt.js :
```
node.error(JSON.parse(body).errors[0].message);
```
It seems that you assume that body is always parseable JSON.  Might be if the server provides a response, but maybe not so on network timeout etc.

As a quick & dirty workaround, I wrapped the parse in a try/catch (which you should probably do regardless anyway):
```
try {
            node.error(JSON.parse(body).errors[0].message);
} catch (err) {
            console.log("Error parsing body (" + body + ") - json parser error:" + err);
}
```

Suggest though, that you have a look at the logic of the test, as, if there is a timeout error, you'll be falling through to the JSON parse, but without necessarily a body which is suitable -
```
!error && response.statusCode === 200
```

Finally, documentation for the request library strongly suggests also setting a timeout, otherwise you could be hanging around for many minutes waiting for a response, which would be less than good.  Might be worth considering...

Cheers!

**Comment by lorenwest** [comment]
Apologies for this taking so long to get to. Published these changes today on v0.3.0

Thank you for your input!
