### ISSUE TITLE
Some ameliorations

### ISSUE THREAD

**Issue by Quentintin** [diegopamio/node-red-contrib-ifttt#16]
Hello,

- You should update web request to new name of maker : **Webhook**
- It could be fine to pass `EventName` as input field into `msg.payload.eventName` field. After this you just have to detect it with :

```js
var eventName;
if(msg.payload.eventName!= undefined){ 
    eventName = msg.payload.event
}
else eventName = node.config.eventName
```
Thks :)

**Comment by lorenwest** [comment]
Done in https://github.com/diegopamio/node-red-contrib-ifttt/blob/master/nodes/ifttt.js#L25
