### ISSUE TITLE
IFTTT_CONNECTION_TIMEOUT_MS undefined

### ISSUE THREAD

**Issue by Onixarts** [diegopamio/node-red-contrib-ifttt#20]
Just installed new version with timeout commited and has an error in debug window:

`"ReferenceError: IFTTT_CONNECTION_TIMEOUT_MS is not defined"`

**Comment by Onixarts** [comment]
P.S. You have a typo IFTT_ vs IFTTT_

**Comment by lorenwest** [comment]
Thanks for catching that! Fixed, committed, and published as 0.3.1
