### ISSUE TITLE
I can't get value1,2,3 parameters to work

### ISSUE THREAD

**Issue by mcgurk** [diegopamio/node-red-contrib-ifttt#3]
I use Raspberry Pi 2. I tried everything to get value1,2,3 -parameters to http request. Then I tested to modify code and after this it worked. I added "json:" and another curly brackets  (I don't know much about javascript, I just found some examples with "json:" with google).
~/.node-red/node_modules/node-red-contrib-ifttt/nodes/ifttt.js:
      request.post('https://maker.ifttt.com/trigger/' + node.config.eventName + '/with/key/' + node.key.credentials.key, { json: {
        value1: msg.payload.value1,
        value2: msg.payload.value2,
        value3: msg.payload.value3
      }}, function (error, response, body) {

**Comment by RackyRose** [comment]
https://github.com/diegopamio/node-red-contrib-ifttt/blob/master/nodes/ifttt.js 
you may use this version.
`
     request({
        uri: 'https://maker.ifttt.com/trigger/' + node.config.eventName + '/with/key/' + node.key.credentials.key,
        method: 'POST',
        json: {
          value1: msg.payload.value1,
          value2: msg.payload.value2,
          value3: msg.payload.value3
        }
      }, function (error, response, body) {
`

**Comment by Mehradzie** [comment]
Could you please put a pull-request on the modified version so the author would approve it.

**Comment by lorenwest** [comment]
Just released 0.0.12, resolving this issue.
