### ISSUE TITLE
the version 0.0.10 now on npmjs.com can't pass value1,value2,value3

### ISSUE THREAD

**Issue by RackyRose** [diegopamio/node-red-contrib-ifttt#4]
https://www.npmjs.com/package/node-red-contrib-ifttt 
 current version is 0.0.10 , and when use npm to install node-red-contrib-ifttt.
It can't pass value1 , value2 , value3 .
I saw your new code on git are upated . And it can finish the job.
Please publish it to npmjs.com again.

**Comment by Mehradzie** [comment]
Wish I seen this 3 hours earlier 😢 Chased my tail for a while and then came up with this URL on the HTTP Request node. It works at least 😄 

`https://maker.ifttt.com/trigger/EVENT_NAME_HERE/with/key/xxxxxxxKEY_HERExxxxxxx?value1={{payload}}`

and payload is just a string passed to it say `msg.payload = "foo"`

You can go ahead and add value2,3 etc.

**Comment by diegopamio** [comment]
I think it is working now, sorry for the delay, I was on vacations.

**Comment by stubbers** [comment]
This isn't fixed unfortunately. 0.0.11 still has:

`      request.post('https://maker.ifttt.com/trigger/' + node.config.eventName + '/with/key/' + node.key.credentials.key, {
        value1: msg.payload.value1,
        value2: msg.payload.value2,
        value3: msg.payload.value3
      }, function (error, response, body) {`

Which doesn't work
