### ISSUE TITLE
please release 0.0.12

### ISSUE THREAD

**Issue by corbosman** [diegopamio/node-red-contrib-ifttt#5]
Could you please release a 0.0.12 so we can use the value1/2/3 again with ifttt.

Thanks

**Comment by PerryWu** [comment]
previous version with following codes work well with value1,2,3.
But the latest 0.0.11 use request.post.

Please check and help release new version. thanks.
`request({
 uri: 'https://maker.ifttt.com/trigger/' + node.config.eventName + '/with/key/' + node.key.credentials.key,
 method: 'POST',
 json: {
 value1: msg.payload.value1,
 value2: msg.payload.value2,
 value3: msg.payload.value3
 }`

**Comment by vossilius** [comment]
+1 passing values to IFTTT doesn't work for me either

**Comment by lorenwest** [comment]
Please update the package.json version in master to 0.0.12 and publish to NPM. This module does not work with the current 0.0.11 published in NPM.  The code was fixed last October, and it's time to push those fixes to NPM so people installing from the node-red console can enjoy this module.

Thank you!

**Comment by lorenwest** [comment]
Released 0.0.12 today, fixing the issue that prevented value1-3 from being sent to IFTTT.
