### ISSUE TITLE
Shared repo maintenance

### ISSUE THREAD

**Issue by lorenwest** [diegopamio/node-red-contrib-ifttt#6]
Hi @diegopamio,

It appears you haven't had much time for this repo. I maintain other node-red-contrib modules and some popular NodeJS modules, and would be happy to help maintain node-red-contrib-ifttt as I feel it's an important module.

As you say, it's not that hard to manually interact with IFTTT, but having a module adds credibility, and it's a place to hold documentation, making it easier for folks to bridge node-red with IFTTT.

Would you entertain adding me as a maintainer for this project in github and NPM? I've been wanting to build the inbound IFTTT side, and would add that over time as well.

-Loren

**Comment by diegopamio** [comment]
Sure, you're right, I'm having little time nowadays to keep things going with this repo. I'll add you as maintainer.

**Comment by diegopamio** [comment]
Done! Thanks for jumping in and collaborating!

**Comment by lorenwest** [comment]
Glad to help out. Would you mind allowing me to publish to npm?

```
npm owner add npm@lorenwest.com node-red-contrib-ifttt
```
