### ISSUE TITLE
Node crashes if no payload

### ISSUE THREAD

**Issue by nicklasl** [diegopamio/node-red-contrib-ifttt#8]
The node crashes if `msg.payload` is not set. 
Is the body (val1, val2, val3) really needed by IFTTT?

**Comment by lorenwest** [comment]
Good question. I haven't tried posting without the values or using without a `msg.payload` but would be happy to merge a pull request if you have the time to work through these considerations.

**Comment by nicklasl** [comment]
I'll see what I can do, but I'm not really a node (or javascript) guy 😃

**Comment by lorenwest** [comment]
Have you verified that IFTTT works when passing no value1, value2, or value3 elements?

**Comment by nicklasl** [comment]
Yes, as far as creating my own maker webhook and it worked both with and without `msg.payload`. When the requests json payload is an empty object, the values (value1, value2, value3) that show up in IFTTT are just `(none)`.

**Comment by lorenwest** [comment]
Perfect - I'll get this pushed out asap.

**Comment by lorenwest** [comment]
Published today at version 0.0.13

Thanks for the contribution!
